import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
// INIT
import "@/css/reset/reset.scss";
import "@/css/globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <Navbar />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
